/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ProofTypes {
  export type LeaseStruct = {
    tokenId: BigNumberish;
    tenant: AddressLike;
    landlord: AddressLike;
    deposit: BigNumberish;
    ipfsCID: string;
    status: BigNumberish;
  };

  export type LeaseStructOutput = [
    tokenId: bigint,
    tenant: string,
    landlord: string,
    deposit: bigint,
    ipfsCID: string,
    status: bigint
  ] & {
    tokenId: bigint;
    tenant: string;
    landlord: string;
    deposit: bigint;
    ipfsCID: string;
    status: bigint;
  };
}

export declare namespace DepositVault {
  export type DepositInfoStruct = {
    amount: BigNumberish;
    released: boolean;
    tenant: AddressLike;
    landlord: AddressLike;
  };

  export type DepositInfoStructOutput = [
    amount: bigint,
    released: boolean,
    tenant: string,
    landlord: string
  ] & { amount: bigint; released: boolean; tenant: string; landlord: string };
}

export interface ProofInInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createLease"
      | "depositVaultAddress"
      | "finalizeLease"
      | "getLeaseSummary"
      | "initializeContracts"
      | "landlordVerifierAddress"
      | "leaseCompleted"
      | "owner"
      | "pendingLeases"
      | "renounceOwnership"
      | "tenantNFTAddress"
      | "transferOwnership"
      | "verifyLeaseRequest"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LeaseApproved"
      | "LeaseFinalized"
      | "LeaseRejected"
      | "LeaseRequested"
      | "LeaseVerified"
      | "OwnershipLinked"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createLease",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositVaultAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeLease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaseSummary",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeContracts",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "landlordVerifierAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "leaseCompleted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingLeases",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tenantNFTAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyLeaseRequest",
    values: [BigNumberish, boolean, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createLease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositVaultAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeLease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeaseSummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "landlordVerifierAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leaseCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingLeases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tenantNFTAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyLeaseRequest",
    data: BytesLike
  ): Result;
}

export namespace LeaseApprovedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    tokenId: BigNumberish,
    tenant: AddressLike,
    landlord: AddressLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    tokenId: bigint,
    tenant: string,
    landlord: string
  ];
  export interface OutputObject {
    requestId: bigint;
    tokenId: bigint;
    tenant: string;
    landlord: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaseFinalizedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    tenant: AddressLike,
    landlord: AddressLike
  ];
  export type OutputTuple = [tokenId: bigint, tenant: string, landlord: string];
  export interface OutputObject {
    tokenId: bigint;
    tenant: string;
    landlord: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaseRejectedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    tenant: AddressLike,
    reason: string
  ];
  export type OutputTuple = [requestId: bigint, tenant: string, reason: string];
  export interface OutputObject {
    requestId: bigint;
    tenant: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaseRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    tenant: AddressLike,
    landlord: AddressLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    tenant: string,
    landlord: string
  ];
  export interface OutputObject {
    requestId: bigint;
    tenant: string;
    landlord: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaseVerifiedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    approved: boolean,
    comment: string
  ];
  export type OutputTuple = [
    requestId: bigint,
    approved: boolean,
    comment: string
  ];
  export interface OutputObject {
    requestId: bigint;
    approved: boolean;
    comment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipLinkedEvent {
  export type InputTuple = [
    tenantNFT: AddressLike,
    verifier: AddressLike,
    vault: AddressLike
  ];
  export type OutputTuple = [
    tenantNFT: string,
    verifier: string,
    vault: string
  ];
  export interface OutputObject {
    tenantNFT: string;
    verifier: string;
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProofIn extends BaseContract {
  connect(runner?: ContractRunner | null): ProofIn;
  waitForDeployment(): Promise<this>;

  interface: ProofInInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createLease: TypedContractMethod<
    [landlord: AddressLike, ipfsCID: string, deposit: BigNumberish],
    [bigint],
    "payable"
  >;

  depositVaultAddress: TypedContractMethod<[], [string], "view">;

  finalizeLease: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getLeaseSummary: TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [ProofTypes.LeaseStructOutput, DepositVault.DepositInfoStructOutput] & {
        lease: ProofTypes.LeaseStructOutput;
        depositInfo: DepositVault.DepositInfoStructOutput;
      }
    ],
    "view"
  >;

  initializeContracts: TypedContractMethod<
    [
      _tenantNFT: AddressLike,
      _landlordVerifier: AddressLike,
      _depositVault: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  landlordVerifierAddress: TypedContractMethod<[], [string], "view">;

  leaseCompleted: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingLeases: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean] & {
        requestId: bigint;
        tenant: string;
        landlord: string;
        ipfsCID: string;
        deposit: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  tenantNFTAddress: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyLeaseRequest: TypedContractMethod<
    [requestId: BigNumberish, approved: boolean, comment: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createLease"
  ): TypedContractMethod<
    [landlord: AddressLike, ipfsCID: string, deposit: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositVaultAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalizeLease"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getLeaseSummary"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [ProofTypes.LeaseStructOutput, DepositVault.DepositInfoStructOutput] & {
        lease: ProofTypes.LeaseStructOutput;
        depositInfo: DepositVault.DepositInfoStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initializeContracts"
  ): TypedContractMethod<
    [
      _tenantNFT: AddressLike,
      _landlordVerifier: AddressLike,
      _depositVault: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "landlordVerifierAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "leaseCompleted"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingLeases"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean] & {
        requestId: bigint;
        tenant: string;
        landlord: string;
        ipfsCID: string;
        deposit: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tenantNFTAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyLeaseRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish, approved: boolean, comment: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "LeaseApproved"
  ): TypedContractEvent<
    LeaseApprovedEvent.InputTuple,
    LeaseApprovedEvent.OutputTuple,
    LeaseApprovedEvent.OutputObject
  >;
  getEvent(
    key: "LeaseFinalized"
  ): TypedContractEvent<
    LeaseFinalizedEvent.InputTuple,
    LeaseFinalizedEvent.OutputTuple,
    LeaseFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "LeaseRejected"
  ): TypedContractEvent<
    LeaseRejectedEvent.InputTuple,
    LeaseRejectedEvent.OutputTuple,
    LeaseRejectedEvent.OutputObject
  >;
  getEvent(
    key: "LeaseRequested"
  ): TypedContractEvent<
    LeaseRequestedEvent.InputTuple,
    LeaseRequestedEvent.OutputTuple,
    LeaseRequestedEvent.OutputObject
  >;
  getEvent(
    key: "LeaseVerified"
  ): TypedContractEvent<
    LeaseVerifiedEvent.InputTuple,
    LeaseVerifiedEvent.OutputTuple,
    LeaseVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipLinked"
  ): TypedContractEvent<
    OwnershipLinkedEvent.InputTuple,
    OwnershipLinkedEvent.OutputTuple,
    OwnershipLinkedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "LeaseApproved(uint256,uint256,address,address)": TypedContractEvent<
      LeaseApprovedEvent.InputTuple,
      LeaseApprovedEvent.OutputTuple,
      LeaseApprovedEvent.OutputObject
    >;
    LeaseApproved: TypedContractEvent<
      LeaseApprovedEvent.InputTuple,
      LeaseApprovedEvent.OutputTuple,
      LeaseApprovedEvent.OutputObject
    >;

    "LeaseFinalized(uint256,address,address)": TypedContractEvent<
      LeaseFinalizedEvent.InputTuple,
      LeaseFinalizedEvent.OutputTuple,
      LeaseFinalizedEvent.OutputObject
    >;
    LeaseFinalized: TypedContractEvent<
      LeaseFinalizedEvent.InputTuple,
      LeaseFinalizedEvent.OutputTuple,
      LeaseFinalizedEvent.OutputObject
    >;

    "LeaseRejected(uint256,address,string)": TypedContractEvent<
      LeaseRejectedEvent.InputTuple,
      LeaseRejectedEvent.OutputTuple,
      LeaseRejectedEvent.OutputObject
    >;
    LeaseRejected: TypedContractEvent<
      LeaseRejectedEvent.InputTuple,
      LeaseRejectedEvent.OutputTuple,
      LeaseRejectedEvent.OutputObject
    >;

    "LeaseRequested(uint256,address,address)": TypedContractEvent<
      LeaseRequestedEvent.InputTuple,
      LeaseRequestedEvent.OutputTuple,
      LeaseRequestedEvent.OutputObject
    >;
    LeaseRequested: TypedContractEvent<
      LeaseRequestedEvent.InputTuple,
      LeaseRequestedEvent.OutputTuple,
      LeaseRequestedEvent.OutputObject
    >;

    "LeaseVerified(uint256,bool,string)": TypedContractEvent<
      LeaseVerifiedEvent.InputTuple,
      LeaseVerifiedEvent.OutputTuple,
      LeaseVerifiedEvent.OutputObject
    >;
    LeaseVerified: TypedContractEvent<
      LeaseVerifiedEvent.InputTuple,
      LeaseVerifiedEvent.OutputTuple,
      LeaseVerifiedEvent.OutputObject
    >;

    "OwnershipLinked(address,address,address)": TypedContractEvent<
      OwnershipLinkedEvent.InputTuple,
      OwnershipLinkedEvent.OutputTuple,
      OwnershipLinkedEvent.OutputObject
    >;
    OwnershipLinked: TypedContractEvent<
      OwnershipLinkedEvent.InputTuple,
      OwnershipLinkedEvent.OutputTuple,
      OwnershipLinkedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
