/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IDepositVault {
  export type DepositInfoStruct = {
    amount: BigNumberish;
    released: boolean;
    tenant: AddressLike;
    landlord: AddressLike;
  };

  export type DepositInfoStructOutput = [
    amount: bigint,
    released: boolean,
    tenant: string,
    landlord: string
  ] & { amount: bigint; released: boolean; tenant: string; landlord: string };
}

export interface IDepositVaultInterface extends Interface {
  getFunction(
    nameOrSignature: "deposit" | "getDepositInfo" | "releaseDeposit"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseDeposit",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDepositInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseDeposit",
    data: BytesLike
  ): Result;
}

export interface IDepositVault extends BaseContract {
  connect(runner?: ContractRunner | null): IDepositVault;
  waitForDeployment(): Promise<this>;

  interface: IDepositVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deposit: TypedContractMethod<
    [tokenId: BigNumberish, tenant: AddressLike, landlord: AddressLike],
    [void],
    "payable"
  >;

  getDepositInfo: TypedContractMethod<
    [tokenId: BigNumberish],
    [IDepositVault.DepositInfoStructOutput],
    "view"
  >;

  releaseDeposit: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [tokenId: BigNumberish, tenant: AddressLike, landlord: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getDepositInfo"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [IDepositVault.DepositInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "releaseDeposit"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  filters: {};
}
