/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ILandlordVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "isTenantApproved"
      | "preApproveTenant"
      | "verificationPassed"
      | "verifyRecord"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isTenantApproved",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "preApproveTenant",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationPassed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyRecord",
    values: [BigNumberish, boolean, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "isTenantApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "preApproveTenant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationPassed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyRecord",
    data: BytesLike
  ): Result;
}

export interface ILandlordVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): ILandlordVerifier;
  waitForDeployment(): Promise<this>;

  interface: ILandlordVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isTenantApproved: TypedContractMethod<
    [tenant: AddressLike],
    [boolean],
    "view"
  >;

  preApproveTenant: TypedContractMethod<
    [tenant: AddressLike, comment: string],
    [void],
    "nonpayable"
  >;

  verificationPassed: TypedContractMethod<
    [tokenId: BigNumberish],
    [boolean],
    "view"
  >;

  verifyRecord: TypedContractMethod<
    [tokenId: BigNumberish, approved: boolean, comment: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isTenantApproved"
  ): TypedContractMethod<[tenant: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "preApproveTenant"
  ): TypedContractMethod<
    [tenant: AddressLike, comment: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verificationPassed"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyRecord"
  ): TypedContractMethod<
    [tokenId: BigNumberish, approved: boolean, comment: string],
    [void],
    "nonpayable"
  >;

  filters: {};
}
