/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDepositVault } from "./IDepositVault";
export type { ILandlordVerifier } from "./ILandlordVerifier";
export type { IProofAccess } from "./IProofAccess";
export type { ITenantNFT } from "./ITenantNFT";
