/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ITenantNFTInterface extends Interface {
  getFunction(
    nameOrSignature: "getLeaseInfo" | "mintTenantNFT" | "totalMinted"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getLeaseInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintTenantNFT",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalMinted",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getLeaseInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintTenantNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalMinted",
    data: BytesLike
  ): Result;
}

export interface ITenantNFT extends BaseContract {
  connect(runner?: ContractRunner | null): ITenantNFT;
  waitForDeployment(): Promise<this>;

  interface: ITenantNFTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getLeaseInfo: TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [bigint, string, string, bigint, string, bigint] & {
        tokenId_: bigint;
        tenant: string;
        landlord: string;
        deposit: bigint;
        ipfsCID: string;
        status: bigint;
      }
    ],
    "view"
  >;

  mintTenantNFT: TypedContractMethod<
    [landlord: AddressLike, ipfsCID: string, deposit: BigNumberish],
    [void],
    "payable"
  >;

  totalMinted: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getLeaseInfo"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [bigint, string, string, bigint, string, bigint] & {
        tokenId_: bigint;
        tenant: string;
        landlord: string;
        deposit: bigint;
        ipfsCID: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintTenantNFT"
  ): TypedContractMethod<
    [landlord: AddressLike, ipfsCID: string, deposit: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "totalMinted"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
