/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DepositVault } from "./DepositVault";
export type { LandlordVerifier } from "./LandlordVerifier";
export type { ProofAccess } from "./ProofAccess";
export type { ProofTypes } from "./ProofTypes";
export type { TenantNFT } from "./TenantNFT";
