/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface LandlordVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getVerificationResult"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "verificationComments"
      | "verificationPassed"
      | "verifyRecord"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred" | "Verified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getVerificationResult",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationComments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationPassed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyRecord",
    values: [BigNumberish, boolean, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getVerificationResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationComments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationPassed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyRecord",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifiedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    landlord: AddressLike,
    approved: boolean,
    comment: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    landlord: string,
    approved: boolean,
    comment: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    landlord: string;
    approved: boolean;
    comment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LandlordVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): LandlordVerifier;
  waitForDeployment(): Promise<this>;

  interface: LandlordVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getVerificationResult: TypedContractMethod<
    [tokenId: BigNumberish],
    [[boolean, string] & { passed: boolean; comment: string }],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verificationComments: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  verificationPassed: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  verifyRecord: TypedContractMethod<
    [tokenId: BigNumberish, approved: boolean, comment: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getVerificationResult"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [[boolean, string] & { passed: boolean; comment: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verificationComments"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "verificationPassed"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyRecord"
  ): TypedContractMethod<
    [tokenId: BigNumberish, approved: boolean, comment: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Verified"
  ): TypedContractEvent<
    VerifiedEvent.InputTuple,
    VerifiedEvent.OutputTuple,
    VerifiedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Verified(uint256,address,bool,string)": TypedContractEvent<
      VerifiedEvent.InputTuple,
      VerifiedEvent.OutputTuple,
      VerifiedEvent.OutputObject
    >;
    Verified: TypedContractEvent<
      VerifiedEvent.InputTuple,
      VerifiedEvent.OutputTuple,
      VerifiedEvent.OutputObject
    >;
  };
}
