/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface ProofTypesInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "ContractCreated"
      | "DepositAdded"
      | "DepositReleased"
      | "LeaseFinalized"
      | "PreApproved"
      | "Verified"
  ): EventFragment;
}

export namespace ContractCreatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    tenant: AddressLike,
    landlord: AddressLike,
    deposit: BigNumberish,
    ipfsCID: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    tenant: string,
    landlord: string,
    deposit: bigint,
    ipfsCID: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    tenant: string;
    landlord: string;
    deposit: bigint;
    ipfsCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositAddedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    amount: BigNumberish,
    tenant: AddressLike
  ];
  export type OutputTuple = [tokenId: bigint, amount: bigint, tenant: string];
  export interface OutputObject {
    tokenId: bigint;
    amount: bigint;
    tenant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositReleasedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    amount: BigNumberish,
    tenant: AddressLike
  ];
  export type OutputTuple = [tokenId: bigint, amount: bigint, tenant: string];
  export interface OutputObject {
    tokenId: bigint;
    amount: bigint;
    tenant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaseFinalizedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    tenant: AddressLike,
    landlord: AddressLike
  ];
  export type OutputTuple = [tokenId: bigint, tenant: string, landlord: string];
  export interface OutputObject {
    tokenId: bigint;
    tenant: string;
    landlord: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PreApprovedEvent {
  export type InputTuple = [tenant: AddressLike, landlord: AddressLike];
  export type OutputTuple = [tenant: string, landlord: string];
  export interface OutputObject {
    tenant: string;
    landlord: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifiedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    landlord: AddressLike,
    approved: boolean,
    comment: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    landlord: string,
    approved: boolean,
    comment: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    landlord: string;
    approved: boolean;
    comment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProofTypes extends BaseContract {
  connect(runner?: ContractRunner | null): ProofTypes;
  waitForDeployment(): Promise<this>;

  interface: ProofTypesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "ContractCreated"
  ): TypedContractEvent<
    ContractCreatedEvent.InputTuple,
    ContractCreatedEvent.OutputTuple,
    ContractCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DepositAdded"
  ): TypedContractEvent<
    DepositAddedEvent.InputTuple,
    DepositAddedEvent.OutputTuple,
    DepositAddedEvent.OutputObject
  >;
  getEvent(
    key: "DepositReleased"
  ): TypedContractEvent<
    DepositReleasedEvent.InputTuple,
    DepositReleasedEvent.OutputTuple,
    DepositReleasedEvent.OutputObject
  >;
  getEvent(
    key: "LeaseFinalized"
  ): TypedContractEvent<
    LeaseFinalizedEvent.InputTuple,
    LeaseFinalizedEvent.OutputTuple,
    LeaseFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "PreApproved"
  ): TypedContractEvent<
    PreApprovedEvent.InputTuple,
    PreApprovedEvent.OutputTuple,
    PreApprovedEvent.OutputObject
  >;
  getEvent(
    key: "Verified"
  ): TypedContractEvent<
    VerifiedEvent.InputTuple,
    VerifiedEvent.OutputTuple,
    VerifiedEvent.OutputObject
  >;

  filters: {
    "ContractCreated(uint256,address,address,uint256,string)": TypedContractEvent<
      ContractCreatedEvent.InputTuple,
      ContractCreatedEvent.OutputTuple,
      ContractCreatedEvent.OutputObject
    >;
    ContractCreated: TypedContractEvent<
      ContractCreatedEvent.InputTuple,
      ContractCreatedEvent.OutputTuple,
      ContractCreatedEvent.OutputObject
    >;

    "DepositAdded(uint256,uint256,address)": TypedContractEvent<
      DepositAddedEvent.InputTuple,
      DepositAddedEvent.OutputTuple,
      DepositAddedEvent.OutputObject
    >;
    DepositAdded: TypedContractEvent<
      DepositAddedEvent.InputTuple,
      DepositAddedEvent.OutputTuple,
      DepositAddedEvent.OutputObject
    >;

    "DepositReleased(uint256,uint256,address)": TypedContractEvent<
      DepositReleasedEvent.InputTuple,
      DepositReleasedEvent.OutputTuple,
      DepositReleasedEvent.OutputObject
    >;
    DepositReleased: TypedContractEvent<
      DepositReleasedEvent.InputTuple,
      DepositReleasedEvent.OutputTuple,
      DepositReleasedEvent.OutputObject
    >;

    "LeaseFinalized(uint256,address,address)": TypedContractEvent<
      LeaseFinalizedEvent.InputTuple,
      LeaseFinalizedEvent.OutputTuple,
      LeaseFinalizedEvent.OutputObject
    >;
    LeaseFinalized: TypedContractEvent<
      LeaseFinalizedEvent.InputTuple,
      LeaseFinalizedEvent.OutputTuple,
      LeaseFinalizedEvent.OutputObject
    >;

    "PreApproved(address,address)": TypedContractEvent<
      PreApprovedEvent.InputTuple,
      PreApprovedEvent.OutputTuple,
      PreApprovedEvent.OutputObject
    >;
    PreApproved: TypedContractEvent<
      PreApprovedEvent.InputTuple,
      PreApprovedEvent.OutputTuple,
      PreApprovedEvent.OutputObject
    >;

    "Verified(uint256,address,bool,string)": TypedContractEvent<
      VerifiedEvent.InputTuple,
      VerifiedEvent.OutputTuple,
      VerifiedEvent.OutputObject
    >;
    Verified: TypedContractEvent<
      VerifiedEvent.InputTuple,
      VerifiedEvent.OutputTuple,
      VerifiedEvent.OutputObject
    >;
  };
}
