/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDepositVault,
  IDepositVaultInterface,
} from "../../../contracts/interfaces/IDepositVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tenant",
        type: "address",
      },
      {
        internalType: "address",
        name: "landlord",
        type: "address",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getDepositInfo",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "released",
            type: "bool",
          },
          {
            internalType: "address",
            name: "tenant",
            type: "address",
          },
          {
            internalType: "address",
            name: "landlord",
            type: "address",
          },
        ],
        internalType: "struct IDepositVault.DepositInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "releaseDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDepositVault__factory {
  static readonly abi = _abi;
  static createInterface(): IDepositVaultInterface {
    return new Interface(_abi) as IDepositVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDepositVault {
    return new Contract(address, _abi, runner) as unknown as IDepositVault;
  }
}
