/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILandlordVerifier,
  ILandlordVerifierInterface,
} from "../../../contracts/interfaces/ILandlordVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tenant",
        type: "address",
      },
    ],
    name: "isTenantApproved",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tenant",
        type: "address",
      },
      {
        internalType: "string",
        name: "comment",
        type: "string",
      },
    ],
    name: "preApproveTenant",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "verificationPassed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
      {
        internalType: "string",
        name: "comment",
        type: "string",
      },
    ],
    name: "verifyRecord",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILandlordVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): ILandlordVerifierInterface {
    return new Interface(_abi) as ILandlordVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILandlordVerifier {
    return new Contract(address, _abi, runner) as unknown as ILandlordVerifier;
  }
}
