/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITenantNFT,
  ITenantNFTInterface,
} from "../../../contracts/interfaces/ITenantNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getLeaseInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tenant",
        type: "address",
      },
      {
        internalType: "address",
        name: "landlord",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "deposit",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "ipfsCID",
        type: "string",
      },
      {
        internalType: "uint8",
        name: "status",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "landlord",
        type: "address",
      },
      {
        internalType: "string",
        name: "ipfsCID",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "deposit",
        type: "uint256",
      },
    ],
    name: "mintTenantNFT",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalMinted",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITenantNFT__factory {
  static readonly abi = _abi;
  static createInterface(): ITenantNFTInterface {
    return new Interface(_abi) as ITenantNFTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ITenantNFT {
    return new Contract(address, _abi, runner) as unknown as ITenantNFT;
  }
}
